// Code generated by protoc-gen-eva. DO NOT EDIT.
// source: hello.proto

package hello

import (
	"context"
)

type ISayHelloServiceServer interface {
	Hello(ctx context.Context, req *String) (resp *String, err error)
}

type ISayHelloServiceClient interface {
	Hello(ctx context.Context, req *String) (resp *String, err error)
}
